name: Build - VCPKG

on:
  workflow_dispatch:
    inputs:
      os:
        description: "Operating system"
        required: true
        default: "all"
        type: choice
        options: [all, ubuntu, macos, windows]
      buildtype:
        description: "Build type"
        required: true
        default: "all"
        type: choice
        options: [all, Debug, Release]
      luajit:
        description: "Use LuaJIT"
        required: true
        default: "all"
        type: choice
        options: [all, on, off]

  push:
    branches: [master, v*]

  pull_request:

jobs:
  build-vcpkg:
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }}-${{ matrix.buildtype }}-luajit=${{ matrix.luajit }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        buildtype: [Debug, Release]
        luajit: [on, off]

    env:
      VCPKG_BUILD_TYPE: release

    steps:
      - name: Check matrix vs workflow_dispatch inputs
        if: |
          github.event_name == 'workflow_dispatch' &&
          !(
            (github.event.inputs.os == 'all' || github.event.inputs.os == matrix.os) &&
            (github.event.inputs.buildtype == 'all' || github.event.inputs.buildtype == matrix.buildtype) &&
            (github.event.inputs.luajit == 'all' || github.event.inputs.luajit == matrix.luajit)
          )
        run: exit 0

      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        if: matrix.os == 'ubuntu' && matrix.buildtype == 'Debug'
        with:
          languages: cpp
          queries: +security-extended,security-and-quality
          config: |
            paths-ignore:
              - 'vcpkg/**'

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure & Build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: vcpkg
          configurePresetAdditionalArgs: "['-DUSE_LUAJIT=${{ matrix.luajit }}']"
          buildPreset: vcpkg
          buildPresetAdditionalArgs: "['--config', '${{ matrix.buildtype }}']"

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        if: matrix.os == 'ubuntu' && matrix.buildtype == 'Debug'

      - name: Upload artifact (Linux / macOS)
        if: matrix.os != 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: tfs-${{ matrix.os }}-${{ matrix.buildtype }}-luajit=${{ matrix.luajit }}
          path: ${{ runner.workspace }}/build/${{ matrix.buildtype }}/tfs

      - name: Upload artifact (Windows)
        if: matrix.os == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: tfs-windows-${{ matrix.buildtype }}-luajit=${{ matrix.luajit }}
          path: |
            ${{ runner.workspace }}/build/${{ matrix.buildtype }}/tfs.exe
            ${{ runner.workspace }}/build/${{ matrix.buildtype }}/*.dll
