name: Build - VCPKG

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - v*
  pull_request:

jobs:
  build-vcpkg:
    name: windows-release-luajit-off
    runs-on: windows-latest

    env:
      VCPKG_BUILD_TYPE: release

    steps:
      - uses: actions/checkout@v4

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure with CMake
        run: >
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=Release
          -DUSE_LUAJIT=off
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifact binary (exe)
        uses: actions/upload-artifact@v4
        with:
          name: tfs-windows-release-luajit-off-${{ github.sha }}
          path: |
            build/Release/tfs.exe
            build/Release/*.dll
